# Generated by Django 4.1.7 on 2023-03-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='geo.capital'),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='geo.currency'),
        ),
    ]
