# Generated by Django 4.1.5 on 2023-01-26 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='category',
            new_name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='geo.capital'),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], default='incorrect', max_length=12),
        ),
    ]
