# Generated by Django 4.1.7 on 2023-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_capital_continent_country_currency_language_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('density', models.IntegerField()),
                ('area', models.IntegerField()),
                ('landlocked', models.BooleanField(default=False, null=True)),
                ('lat', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('long', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
            ],
        ),
    ]
