# Generated by Django 4.1 on 2023-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('answers', models.ManyToManyField(to='geo.country')),
            ],
        ),
    ]
