# Generated by Django 4.1 on 2023-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_riddle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='answers',
            field=models.ManyToManyField(related_name='riddles', to='geo.country'),
        ),
    ]
