# Generated by Django 4.1 on 2023-02-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_riddle_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='answers',
            field=models.ManyToManyField(to='geo.country'),
        ),
    ]
