# Generated by Django 4.1.7 on 2023-03-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_country_landlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.capital'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.currency'),
        ),
        migrations.AlterField(
            model_name='country',
            name='landlocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='regions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='geo.region'),
        ),
    ]
