# Generated by Django 4.1 on 2023-02-10 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_riddle_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.country')),
                ('riddle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geo.riddle')),
            ],
        ),
    ]
