# Generated by Django 4.1.7 on 2023-02-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_alter_riddle_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riddle',
            name='date',
        ),
    ]
